import { useEffect, useState } from 'react'
import { Bot, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/Button'
import { Card, CardContent, CardHeader } from '@/components/ui/Card'
import { Input, Textarea } from '@/components/ui/Input'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db: any = supabase
type Counter = { id: string; command: string; label: string; count: number; response_template: string; cooldown_seconds: number }

export function ChatAutomationManager({ streamerId }: { streamerId: string }) {
  const [items, setItems] = useState<Counter[]>([]); const [command, setCommand] = useState(''); const [label, setLabel] = useState(''); const [message, setMessage] = useState('@{target}, essa é a {count}ª vez registrada.'); const [cooldown, setCooldown] = useState('60'); const [editing, setEditing] = useState<string | null>(null)
  const load = async () => { const { data } = await db.from('chat_command_counters').select('*').eq('streamer_id', streamerId).order('created_at'); setItems(data ?? []) }
  useEffect(() => { void load() }, [streamerId])
  const save = async () => { const normalized = `!${command.trim().replace(/^!+/, '').toLowerCase()}`; if (!/^![a-z0-9][a-z0-9_-]{1,30}$/.test(normalized) || !label.trim() || !message.trim()) return toast.error('Preencha comando, nome e mensagem.'); const payload = { label: label.trim(), response_template: message.trim(), cooldown_seconds: Number(cooldown) }; const result = editing ? await db.from('chat_command_counters').update(payload).eq('id', editing) : await db.from('chat_command_counters').insert({ streamer_id: streamerId, command: normalized, ...payload }); if (result.error) return toast.error('Não foi possível salvar o contador.'); setCommand(''); setLabel(''); setMessage('@{target}, essa é a {count}ª vez registrada.'); setCooldown('60'); setEditing(null); void load() }
  const edit = (item: Counter) => { setEditing(item.id); setCommand(item.command); setLabel(item.label); setMessage(item.response_template); setCooldown(String(item.cooldown_seconds)) }
  return <Card className="mt-6"><CardHeader><div><h2 className="flex items-center gap-2 font-semibold text-content-primary"><Bot size={17} className="text-brand-purple" /> Contadores do chat</h2><p className="mt-1 text-xs text-content-muted">A pessoa que usa o comando é contada automaticamente.</p></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-[9rem_1fr_8rem]"><Input value={command} onChange={e => setCommand(e.target.value)} placeholder="!lurker" disabled={Boolean(editing)} /><Input value={label} onChange={e => setLabel(e.target.value)} placeholder="Nome do contador" /><Input type="number" min="0" max="86400" value={cooldown} onChange={e => setCooldown(e.target.value)} hint="Cooldown (seg)" /></div><Textarea value={message} onChange={e => setMessage(e.target.value)} rows={2} hint="Mensagem do bot. Posicione {target} e {count} onde quiser." /><div className="flex gap-2"><Button size="sm" onClick={save} leftIcon={<Plus size={14}/>}>{editing ? 'Salvar contador' : 'Novo contador'}</Button>{editing && <Button size="sm" variant="ghost" onClick={() => setEditing(null)}>Cancelar</Button>}</div><p className="text-xs text-content-muted">Exemplo: “{message.replaceAll('{target}', 'Thenees').replaceAll('{count}', '10')}”</p>{items.map(item => <div key={item.id} className="rounded-xl border border-border p-3"><div className="flex items-center gap-3"><code className="text-xs text-brand-purple">{item.command}</code><p className="flex-1 text-xs">{item.label}: <strong>{item.count}</strong> · {item.cooldown_seconds}s</p><Button size="sm" variant="secondary" onClick={() => edit(item)}>Editar</Button><Button size="sm" variant="danger" onClick={async () => { await db.from('chat_command_counters').delete().eq('id', item.id); void load() }}><Trash2 size={13}/></Button></div><p className="mt-2 text-xs text-content-muted">{item.response_template}</p></div>)}</CardContent></Card>
}
