import { useEffect, useState } from 'react'
import { Bot, Clock3, Plus, Trash2, Trophy } from 'lucide-react'
import { toast } from 'sonner'
import { supabase } from '@/lib/supabase'
import { Button } from '@/components/ui/Button'
import { Card, CardContent, CardHeader } from '@/components/ui/Card'
import { Input, Textarea } from '@/components/ui/Input'

// New automation tables are introduced by migration 0056.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db: any = supabase
type Timed = { id: string; kind: 'message' | 'poll_leader'; message: string; interval_minutes: number; enabled: boolean }
type Command = { id: string; command: string; response: string; enabled: boolean }

export function ChatAutomationManager({ streamerId }: { streamerId: string }) {
  const [timers, setTimers] = useState<Timed[]>([]); const [commands, setCommands] = useState<Command[]>([])
  const [message, setMessage] = useState(''); const [minutes, setMinutes] = useState('15'); const [command, setCommand] = useState(''); const [response, setResponse] = useState('')
  const load = async () => { const [t, c] = await Promise.all([db.from('chat_timed_messages').select('*').eq('streamer_id', streamerId).order('created_at'), db.from('chat_custom_commands').select('*').eq('streamer_id', streamerId).order('created_at')]); if (!t.error) setTimers(t.data ?? []); if (!c.error) setCommands(c.data ?? []) }
  useEffect(() => { void load() }, [streamerId])
  const addTimer = async (kind: Timed['kind']) => { const text = kind === 'poll_leader' ? '🏆 {viewer} é quem mais participou desta votação, com {votos} votos!' : message.trim(); if (!text) return toast.error('Escreva a mensagem que será enviada.'); const { error } = await db.from('chat_timed_messages').insert({ streamer_id: streamerId, kind, message: text, interval_minutes: Number(minutes) }); if (error) return toast.error('Não foi possível salvar o timer.'); setMessage(''); toast.success('Timer criado.'); void load() }
  const addCommand = async () => { const normalized = `!${command.trim().replace(/^!+/, '').toLowerCase()}`; if (!/^![a-z0-9][a-z0-9_-]{1,30}$/.test(normalized) || !response.trim()) return toast.error('Informe um comando e uma resposta válidos.'); const { error } = await db.from('chat_custom_commands').insert({ streamer_id: streamerId, command: normalized, response: response.trim() }); if (error) return toast.error('Esse comando já existe ou não pôde ser salvo.'); setCommand(''); setResponse(''); toast.success('Comando criado.'); void load() }
  const remove = async (table: string, id: string) => { const { error } = await db.from(table).delete().eq('id', id); if (error) return toast.error('Não foi possível remover.'); void load() }
  return <Card className="mt-6"><CardHeader><div><h2 className="flex items-center gap-2 font-semibold text-content-primary"><Bot size={17} className="text-brand-purple" /> Automações do chat</h2><p className="mt-1 text-xs text-content-muted">Mensagens recorrentes e respostas para comandos do seu canal.</p></div></CardHeader><CardContent className="space-y-6"><section className="space-y-3"><div className="flex items-center gap-2"><Clock3 size={16} className="text-brand-purple" /><p className="text-sm font-semibold">Mensagens com timer</p></div><div className="grid gap-2 sm:grid-cols-[1fr_8rem_auto]"><Textarea aria-label="Mensagem recorrente" value={message} onChange={e => setMessage(e.target.value)} placeholder="Ex.: Siga o canal para não perder a próxima votação!" rows={2} /><Input aria-label="Intervalo em minutos" type="number" min="5" max="240" value={minutes} onChange={e => setMinutes(e.target.value)} /><Button size="sm" onClick={() => addTimer('message')} leftIcon={<Plus size={14} />}>Adicionar</Button></div><Button size="sm" variant="outline" onClick={() => addTimer('poll_leader')} leftIcon={<Trophy size={14} />}>Destacar líder da votação</Button><p className="text-[11px] text-content-muted">O destaque usa {'{viewer}'} e {'{votos}'} automaticamente e só envia enquanto houver uma votação ativa.</p>{timers.map(timer => <div key={timer.id} className="flex items-center gap-3 rounded-xl border border-border bg-bg-tertiary p-3"><p className="min-w-0 flex-1 text-xs text-content-secondary">{timer.kind === 'poll_leader' ? '🏆 Líder da votação' : timer.message} · a cada {timer.interval_minutes} min</p><Button size="sm" variant="danger" onClick={() => remove('chat_timed_messages', timer.id)} leftIcon={<Trash2 size={13} />}>Remover</Button></div>)}</section><section className="space-y-3 border-t border-border pt-5"><p className="text-sm font-semibold">Comandos personalizados</p><div className="grid gap-2 sm:grid-cols-[9rem_1fr_auto]"><Input aria-label="Comando personalizado" value={command} onChange={e => setCommand(e.target.value)} placeholder="!discord" /><Input aria-label="Resposta do comando" value={response} onChange={e => setResponse(e.target.value)} placeholder="Entre no Discord: ..." /><Button size="sm" onClick={addCommand} leftIcon={<Plus size={14} />}>Adicionar</Button></div>{commands.map(item => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-border bg-bg-tertiary p-3"><code className="text-xs text-brand-purple">{item.command}</code><p className="min-w-0 flex-1 truncate text-xs text-content-secondary">{item.response}</p><Button size="sm" variant="danger" onClick={() => remove('chat_custom_commands', item.id)} leftIcon={<Trash2 size={13} />}>Remover</Button></div>)}</section></CardContent></Card>
}
